### ISSUE TITLE
Word list

### ISSUE THREAD

**Issue by rmc3** [strackoverflow/wordchecker#1]
I've noticed that the word list isn't completely accurate relative to the current Words With Friends. For example 'zen' is not in the list, yet is an allowed word in Words With Friends per my personal experience. How are you generating the words.txt file? Notice there's only been one month-old commit.

**Comment by strackoverflow** [comment]
That's true. Zynga linked to the "Enhanced North American Benchmark Lexicon" text file which is included in Wordchecker, but it does not include any custom additions by Zynga (such as "zen"). As far as I can tell, there's no way to really get those types of words. The current text file should cover 99% of the words, though. 

I'm willing to accept pull requests though that add missing words to the text file.

**Comment by brucemc65** [comment]
Hi Dave, l love your app and use it all the time between moves with WWF to try possible words. I noticed that some 2 letter words are missing. "za" and "qi". There were others too I can't recall. Just a heads up.

**Comment by brucemc65** [comment]
"ki" is aslo unrecognized. Should I be making these comments elsewhere? It doesn't appear that you
